<?xml version="1.0" encoding="utf-8"?><Database Name="ReportKCS" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=192.168.2.3;Initial Catalog=ReportKCS;Persist Security Info=True;User ID=talll" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ReportKCSConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ReportKeyIn" Member="ReportKeyIn">
    <Type Name="ReportKeyIn">
      <Column Name="ReportKeyInID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SubjectID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Num1" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Num2" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Num3" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="ReportDate" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Subject" Member="Subject">
    <Type Name="Subject">
      <Column Name="SubjectID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Num" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Layer" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="SubOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.News" Member="News">
    <Type Name="News">
      <Column Name="NewsID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NewsType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NewsContent" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="InsertDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>